using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AutoMapper;
using DSH.Access.UserAccess;
using DSH.Access.DataModels;
using DSH.DataAccess.Services;
using DSH.Main.Web.Services;
using NUnit.Framework;

namespace DSH.DataAccess.Test
{
    [TestFixture]
    public class DiskAccessTest
    {
        private Users _userInfo;
        private string _picturesFolder;
        private string _fileName;
        private string _profilePictureFilePath;
        private string _serverPath;
       
        [SetUp]
        public void Init()
        {
            Configure();

            _userInfo = new Users
                           {
                               CreationDate = null,
                               DisplayName = "Roshan Dhananjaya",
                               Downvotes = 0,
                               Id = 0,
                               LastAccessDate = null,
                               PicLocation = @"http://m3.licdn.com/mpr/mprx/0_hTReA02tQ-nNRf3AhkocAyg7ktlUJuAAGLfcAy2tUq5w6H6lubIkxpZyExAkswrj3CJnOR-7wMtM",
                               PublicProfileUrl = @"http://www.linkedin.com/in/roshandhananajaya",
                               Reputation = 0,
                               UserUniqueid = "szaF9K6odR",
                               Upvotes = 0,
                               Views = 0
                           };

            _picturesFolder = "image_store";
            // have to set this manually for each project
            _serverPath = @"D:\WorkDir\DoitShareit\DoitShareIt.git\branches\R117\DSH.Main.Web"; 

            DiskDataAccess.ProfilePicturePath(_userInfo, _serverPath, _picturesFolder, out _fileName, out _profilePictureFilePath);



        }

        [Test]
        public void TestFileName()
        {
// todo: check whether file name generated by function is correct

            Assert.AreEqual(_fileName, "794440113172189291352261931191312262321647247122116246.jpg");

        }

        [Test]
        public void TestProfilePictureFilePath()
        {

            // check for correctness of the file path
            Assert.AreEqual(_profilePictureFilePath,
                          @"D:\WorkDir\DoitShareit\DoitShareIt.git\branches\R117\DSH.Main.Web\image_store\794440113172189291352261931191312262321647247122116246.jpg");
        }



        private void Configure()
        {
            
            
        }
    }


}
